name: SonarCloud Scan

on:
  pull_request:
    branches:
      - master
      
env:
  prNumber: ${{ github.event.pull_request.number }}
  prBranch: ${{ github.ref_name }}
  baseBranch: ${{ github.event.pull_request.base.ref }}

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: SonarScan
      run: ./gradlew build sonarqube --info -Dsonar.organization="HMCTS" -Dsonar.pullrequest.base="${{ env.baseBranch }}" -Dsonar.pullrequest.branch="${{ env.prBranch }}"  -Dsonar.pullrequest.provider="github"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
