name: Unit Test

on:
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Build
        run: ./gradlew clean build

      - name: Test
        run: ./gradlew test
